name = "bestlettingagentforlandlords"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[vars]
BREVO_SENDER_EMAIL = "hello@bestlettingagentforlandlords.co.uk"
CONTACT_TO = "hello@bestlettingagentforlandlords.co.uk"
